esphome:
  name: breadboard
  friendly_name: Breadboard

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "bBSafKkRoBWiXT2fL06S/IIUCi1MaUTK+pD1mRHFTfg="

ota:
  - platform: esphome
    password: "be383e11f52732210a391a3b638eaa8c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Breadboard Fallback Hotspot"
    password: "OwuzPDHNIV8p"

captive_portal:

time:
 - platform: sntp

web_server:
  port: 80
  ota: false
  version: 3

# Individual sensors
sensor:
      
# Some Dianostic info
  - platform: wifi_signal
    name: "ESP Wifi Signal"
#    update_interval: 60s

text_sensor:    
# Lets add some sensors about this devices
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP SSID
    bssid:
      name: ESP BSSID
    mac_address:
      name: ESP Mac Wifi Address
    dns_address:
      name: ESP DNS Address

  - platform: version
    name: "ESPHome Version"

output:
  - platform: gpio # Configure Button on GPIO32
    pin: GPIO32
    id: button_push_gpio32

  - platform: gpio # Configure LED on GPIO4
    pin: GPIO4
    id: led_gpio4

button:
  - platform: output
    name: "DoorButton"
    id: "doorbutton"
    output: button_push_gpio32
    duration: 300 ms

light:
  - platform: binary
    name: "Breadboard LED"
    output: led_gpio4
  
  - platform: status_led
    name: "Status LED"
    pin: GPIO2